<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            elementFormDefault="qualified">

    <xsd:element name="order">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="orderId" type="xsd:string"/>
                <xsd:element name="customerId" type="xsd:string"/>
                <xsd:element name="status" type="xsd:string"/>
                <xsd:element name="currency" type="xsd:string"/>
                <xsd:element name="orderTotal" type="xsd:decimal"/>
                <xsd:element name="items">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="item" maxOccurs="unbounded">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="sku" type="xsd:string"/>
                                        <xsd:element name="quantity" type="xsd:integer"/>
                                        <xsd:element name="unitPrice" type="xsd:decimal"/>
                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

</xsd:schema>
